[package]
name = "aoc_2020"
version.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
edition = "2018"

[dependencies]
regex = "1"
itertools = "0.9"
pathfinding = "2.1.1"
